name: Health Checking
on: push
jobs:
  build:
    name: Elixir ${{matrix.elixir}} / OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: [21.x, 22.x]
        elixir: [1.8.x, 1.9.x]
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1.0.0

      - uses: actions/setup-elixir@1.0.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Check Linter
        run: mix credo

      - name: Run Tests
        run: mix coveralls.json
        env:
          CI_DB_HOSTNAME: db

      - name: Upload Coverage
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Check Typespec
        run: mix dialyzer --halt-exit-status
